config/routes.rb
BQnected::Application.routes.draw do

  resources :alerts

  devise_for :usuarios

  resources :comentarios#, only: [ :new, :create, :destroy]

  resources :barrios

  resources :eventos

  resources :usuarios

  root :to => 'eventos#index'

end

app/models/evento.rb
class Evento < ActiveRecord::Base
  attr_accessible :asistentes, :barrio_id, :descripcion, :fecha, :hora, :nombre, :tipo, :ubicacion, :comentarios

  belongs_to :barrio
  has_many :comentarios
end

app/controllers/eventos_controller.rb
class EventosController < ApplicationController
  # GET /eventos
  # GET /eventos.json
  before_filter :authenticate_usuario!, only: [:new, :create, :edit, :update, :destroy]
  def index
    @eventos = Evento.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @eventos }
    end
  end

  # GET /eventos/1
  # GET /eventos/1.json
  def show
    @evento = Evento.find(params[:id])
    @comentario = Comentario.new  
    @comentar= Comentario.all   
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @evento }
    end
  end

  # GET /eventos/new
  # GET /eventos/new.json
  def new
    @evento = Evento.new
    @barrios = Barrio.all.map { |bar| [bar.nombre, bar.id]  }
    @tiposEvento = ["Cultural", "Deportivo", "Musical", "Politico", "Religioso", "Academico", "Fiesta", "Gastronomico"]
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @evento }
    end
  end

  # GET /eventos/1/edit
  def edit
    @barrios = Barrio.all.map { |bar| [bar.nombre, bar.id]  }
    @evento = Evento.find(params[:id])
    @tiposEvento = ["Cultural", "Deportivo", "Musical", "Politico", "Religioso", "Academico", "Fiesta", "Gastronomico"]
  end

  # POST /eventos
  # POST /eventos.json
  def create
    @evento = Evento.new(params[:evento])

    respond_to do |format|
      if @evento.save
        format.html { redirect_to @evento, notice: 'Evento was successfully created.' }
        format.json { render json: @evento, status: :created, location: @evento }
      else
        format.html { render action: "new" }
        format.json { render json: @evento.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /eventos/1
  # PUT /eventos/1.json
  def update
    @evento = Evento.find(params[:id])

    respond_to do |format|
      if @evento.update_attributes(params[:evento])
        format.html { redirect_to @evento, notice: 'Evento was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @evento.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /eventos/1
  # DELETE /eventos/1.json
  def destroy
    @evento = Evento.find(params[:id])
    @evento.destroy

    respond_to do |format|
      format.html { redirect_to eventos_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/eventos_helper.rb
module EventosHelper
end

app/views/eventos/_form.html.erb
<%= form_for(@evento) do |f| %>
  <% if @evento.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@evento.errors.count, "error") %> prohibited this evento from being saved:</h2>

      <ul>
      <% @evento.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %><br />
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
    <%= f.label :tipo %><br />
    <%= f.select :tipo, options_for_select(@tiposEvento) %>
  </div>
  <div class="field">
    <%= f.label :descripcion %><br />
    <%= f.text_area :descripcion %>
  </div>
  <div class="field">
    <%= f.label :fecha %><br />
    <%= f.text_field :fecha %>
  </div>
  <div class="field">
    <%= f.label :barrio_id %><br />
    <%= f.select :barrio_id, options_for_select(@barrios)%>
  </div>
  <div class="field">
    <%= f.label :ubicacion %><br />
    <%= f.text_field :ubicacion %>
  </div>
  <div class="field">
    <%= f.label :hora %><br />
    <%= f.time_select :hora %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/eventos/edit.html.erb
<h1>Editing evento</h1>

<%= render 'form' %>

<%= link_to 'Show', @evento %> |
<%= link_to 'Back', eventos_path %>

app/views/eventos/index.html.erb
<% if usuario_signed_in? %>
<h4>Estos son los eventos de tu barrio <%= @BarrioEvento = current_usuario.barrio.try(:nombre) %> </h4>

<table>
  <tr>
    <th>Nombre</th>
    <th>Tipo</th>   
    <th>Ubicacion</th>
    <th>Fecha</th>
    <th>Hora</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

    <% @eventos.each do |evento| %>
      <% if evento.barrio.try(:nombre) == @BarrioEvento %>
          <tr>          
            <td><%= evento.nombre %></td>
            <td><%= evento.tipo %></td>    
            <td><%= evento.ubicacion %></td>
            <td><%= evento.fecha %></td>
            <td><%= evento.hora %></td>
            <td><%= link_to 'Show', evento %></td>
            <td><%= link_to 'Edit', edit_evento_path(evento) %></td>
            <td><%= link_to 'Destroy', evento, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
      <% end %>    
    <% end %>
</table>

<%= link_to 'Nuevo Evento', new_evento_path, class: 'button [tiny small large]' %>
<% else %>
<h2>Estos son todos los eventos disponibles </h2>
    <h5>Ingresa ahora para ver sólo los eventos de tu barrio... o crear uno nuevo!</h5>
<table>
  <tr>
    <th>Nombre</th>
    <th>Barrio</th>
    <th>Fecha</th>
  </tr>
  <% @eventos.each do |evento| %>
  <tr>
    <td><%= evento.nombre %></td>
    <td><%= evento.barrio.try(:nombre)%></td>
    <td><%= evento.fecha %></td>
  </tr>
  <% end %>
</table>
<% end %>

app/views/eventos/new.html.erb
<h1>Nuevo Evento</h1>

<%= render 'form' %>

<%= link_to 'Back', eventos_path %>

app/views/eventos/show.html.erb
<h2>
  <%= @evento.nombre %>
  </br>
</h2>

<p>
  <b>Tipo:</b>
  <%= @evento.tipo %>
</p>

<p>
  <b>Descripcion:</b>
  <%= @evento.descripcion %>
</p>

<p>
  <b>Fecha:</b>
  <%= @evento.fecha %>
</p>

<p>
  <b>Barrio:</b>
  <%= @evento.barrio.try(:nombre) %>
</p>

<p>
  <b>Ubicacion:</b>
  <%= @evento.ubicacion %>
</p>

<p>
  <b>Hora:</b>
  <%= @evento.hora %>
</p>

<h4>Lo que se comenta</h4>
<table>
  <tr>
    <th>Nombre Usuario</th>
    <th>Comentario</th>
  </tr>
  <tr>
    <% @comentar.each do |comment| %>
      <% if comment.evento.id == @evento.id %>
          <tr>          
            <td><%= comment.usuario.nombre %></td>
            <td><%= comment.comentario %></td>    
          </tr>
      <% end %>    
    <% end %>
  </tr>
</table>

<h6>Deja tu comentario</h6>

<%= form_for(@comentario) do |f| %>
  <% if @comentario.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comentario.errors.count, "error") %> prohibited this comentario from being saved:</h2>

      <ul>
      <% @comentario.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label ' ' %>
    <%= f.text_area :comentario %>
  </div>
  <%= hidden_field_tag :evento_id, @evento.id %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<%= social_share_button_tag(@comentario.comentario) %>

<%= link_to 'Edit', edit_evento_path(@evento) %> |
<%= link_to 'Back', eventos_path %>