config/routes.rb
BQnected::Application.routes.draw do

  resources :alerts

  devise_for :usuarios

  resources :comentarios#, only: [ :new, :create, :destroy]

  resources :barrios

  resources :eventos

  resources :usuarios

  root :to => 'eventos#index'

end

app/models/alert.rb
class Alert < ActiveRecord::Base
  belongs_to :barrio
  attr_accessible :contenido, :tipo, :barrio_id
end

app/controllers/alerts_controller.rb
class AlertsController < ApplicationController
  # GET /alerts
  # GET /alerts.json
  def index
    @alerts = Alert.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @alerts }
    end
  end

  # GET /alerts/1
  # GET /alerts/1.json
  def show
    @alert = Alert.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @alert }
    end
  end

  # GET /alerts/new
  # GET /alerts/new.json
  def new
    @alert = Alert.new
    @barrios = Barrio.all.map { |bar| [bar.nombre, bar.id]  }
    @tiposAlertas = ["Accidente","Disputa", "Robo"]
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @alert }
    end
  end

  # GET /alerts/1/edit
  def edit
    @barrios = Barrio.all.map {|bar| [bar.nombre, bar.id]}    
    @alert = Alert.find(params[:id])
    @tiposAlertas = ["Accidente","Disputa", "Robo"]
  end

  # POST /alerts
  # POST /alerts.json
  def create
    @alert = Alert.new(params[:alert])
    @tiposAlertas = ["Accidente","Disputa", "Robo"]
    respond_to do |format|
      if @alert.save
        format.html { redirect_to @alert, notice: 'Alert was successfully created.' }
        format.json { render json: @alert, status: :created, location: @alert }
      else
        format.html { render action: "new" }
        format.json { render json: @alert.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /alerts/1
  # PUT /alerts/1.json
  def update
    @alert = Alert.find(params[:id])

    respond_to do |format|
      if @alert.update_attributes(params[:alert])
        format.html { redirect_to @alert, notice: 'Alert was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @alert.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /alerts/1
  # DELETE /alerts/1.json
  def destroy
    @alert = Alert.find(params[:id])
    @alert.destroy

    respond_to do |format|
      format.html { redirect_to alerts_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/alerts_helper.rb
module AlertsHelper
end

app/views/alerts/_form.html.erb
<%= form_for(@alert) do |f| %>
  <% if @alert.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@alert.errors.count, "error") %> prohibited this alert from being saved:</h2>

      <ul>
      <% @alert.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :contenido %><br />
    <%= f.text_area :contenido %>
  </div>
  <div class="field">
    <%= f.label :tipo %><br />
    <%= f.select :tipo, options_for_select(@tiposAlertas) %>
  </div>
  <div class="field">
    <%= f.label :barrio_id %><br />
    <%= f.select :barrio_id, options_for_select(@barrios) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/alerts/edit.html.erb
<h1>Editing alert</h1>

<%= render 'form' %>

<%= link_to 'Show', @alert %> |
<%= link_to 'Back', alerts_path %>

app/views/alerts/index.html.erb
<h1>Todas las alertas</h1>

<table>
  <tr>
    <th>Contenido</th>
    <th>Tipo</th>
    <th>Barrio</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @alerts.each do |alert| %>
  <tr>
    <td><%= alert.contenido %></td>
    <td><%= alert.tipo %></td>
    <td><%= alert.barrio.nombre %></td>
    <td><%= link_to 'Ver', alert %></td>
    <% if current_usuario.nombre == 'Andres Lastra Terán' %>
    <td><%= link_to 'Editar', edit_alert_path(alert) %></td>
    <td><%= link_to 'Eliminar', alert, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    <% end %>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Alert', new_alert_path, class: 'button [tiny small large]' %>

app/views/alerts/new.html.erb
<h1>Nueva Alerta</h1>

<%= render 'form' %>

<%= link_to 'Back', alerts_path %>

app/views/alerts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Contenido:</b>
  <%= @alert.contenido %>
</p>

<p>
  <b>Tipo:</b>
  <%= @alert.tipo %>
</p>

<p>
  <b>Barrio:</b>
  <%= @alert.barrio.nombre %>
</p>

<%= social_share_button_tag(@alert.tipo) %>
<%= link_to 'Edit', edit_alert_path(@alert) %> |
<%= link_to 'Back', alerts_path %>