config/routes.rb
BQnected::Application.routes.draw do

  resources :alerts

  devise_for :usuarios

  resources :comentarios#, only: [ :new, :create, :destroy]

  resources :barrios

  resources :eventos

  resources :usuarios

  root :to => 'eventos#index'

end

app/models/barrio.rb
class Barrio < ActiveRecord::Base
  attr_accessible :locacion, :nombre

  has_many :eventos
  has_many :usuarios
end

app/controllers/barrios_controller.rb
class BarriosController < ApplicationController
  # GET /barrios
  # GET /barrios.json
  def index
    @barrios = Barrio.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @barrios }
    end
  end

  # GET /barrios/1
  # GET /barrios/1.json
  def show
    @barrio = Barrio.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @barrio }
    end
  end

  # GET /barrios/new
  # GET /barrios/new.json
  def new
    @barrio = Barrio.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @barrio }
    end
  end

  # GET /barrios/1/edit
  def edit
    @barrio = Barrio.find(params[:id])
  end

  # POST /barrios
  # POST /barrios.json
  def create
    @barrio = Barrio.new(params[:barrio])

    respond_to do |format|
      if @barrio.save
        format.html { redirect_to @barrio, notice: 'Barrio was successfully created.' }
        format.json { render json: @barrio, status: :created, location: @barrio }
      else
        format.html { render action: "new" }
        format.json { render json: @barrio.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /barrios/1
  # PUT /barrios/1.json
  def update
    @barrio = Barrio.find(params[:id])

    respond_to do |format|
      if @barrio.update_attributes(params[:barrio])
        format.html { redirect_to @barrio, notice: 'Barrio was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @barrio.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /barrios/1
  # DELETE /barrios/1.json
  def destroy
    @barrio = Barrio.find(params[:id])
    @barrio.destroy

    respond_to do |format|
      format.html { redirect_to barrios_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/barrios_helper.rb
module BarriosHelper
end

app/views/barrios/_form.html.erb
<%= form_for(@barrio) do |f| %>
  <% if @barrio.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@barrio.errors.count, "error") %> prohibited this barrio from being saved:</h2>

      <ul>
      <% @barrio.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %><br />
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
    <%= f.label :locacion %><br />
    <%= f.text_field :locacion %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/barrios/edit.html.erb
<h1>Editar Barrio</h1>

<%= render 'form' %>

<%= link_to 'Show', @barrio %> |
<%= link_to 'Back', barrios_path %>

app/views/barrios/index.html.erb
<h1>Barrios</h1>

<table>
  <tr>
    <th>Nombre</th>
    <th>Municipio</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @barrios.each do |barrio| %>
  <tr>
    <td><%= barrio.nombre %></td>
    <td><%= barrio.locacion %></td>
    <td><%= link_to 'Show', barrio %></td>
    <td><%= link_to 'Edit', edit_barrio_path(barrio) %></td>
    <td><%= link_to 'Destroy', barrio, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Barrio', new_barrio_path %>

app/views/barrios/new.html.erb
<h1>Nuevo Barrio</h1>

<%= render 'form' %>

<%= link_to 'Back', barrios_path %>

app/views/barrios/show.html.erb
<p>
  <b>Nombre:</b>
  <%= @barrio.nombre %>
</p>

<p>
  <b>Locacion:</b>
  <%= @barrio.locacion %>
</p>

<%= link_to 'Edit', edit_barrio_path(@barrio) %> |
<%= link_to 'Back', barrios_path %>